apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: taskmanager
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  # ClusterIP so Postgres is only reachable inside the cluster
  type: ClusterIP